"""
Report MCP Server — generate PDF client briefs via WeasyPrint.
"""
import pathlib
import sys
import base64
sys.path.insert(0, str(pathlib.Path(__file__).parents[2]))

import duckdb
from fastmcp import FastMCP

DB_PATH = str(pathlib.Path(__file__).parents[2] / "frammer.duckdb")

mcp = FastMCP("report_server")
_conn = None


def _db():
    global _conn
    if _conn is None:
        _conn = duckdb.connect(DB_PATH, read_only=True)
    return _conn


_REPORT_HTML = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; margin: 40px; color: #1a1a2e; }}
  h1 {{ color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 8px; }}
  h2 {{ color: #374151; margin-top: 24px; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 12px; }}
  th {{ background: #4f46e5; color: white; padding: 8px 12px; text-align: left; }}
  td {{ padding: 7px 12px; border-bottom: 1px solid #e5e7eb; }}
  tr:nth-child(even) {{ background: #f9fafb; }}
  .metric {{ font-size: 2em; font-weight: bold; color: #4f46e5; }}
  .label {{ color: #6b7280; font-size: 0.9em; }}
  .kpi-card {{ display: inline-block; margin: 12px; padding: 16px 24px;
               background: #f3f4f6; border-radius: 8px; text-align: center; min-width: 140px; }}
</style>
</head>
<body>
<h1>Frammer AI Analytics — Client Brief</h1>
<p class="label">Client: {client_id} | Period: {period}</p>

<h2>Funnel Overview</h2>
<div>
  <div class="kpi-card"><div class="metric">{uploaded}</div><div class="label">Uploaded</div></div>
  <div class="kpi-card"><div class="metric">{processed}</div><div class="label">Processed</div></div>
  <div class="kpi-card"><div class="metric">{published}</div><div class="label">Published</div></div>
  <div class="kpi-card"><div class="metric">{pcr_total}%</div><div class="label">Overall PCR</div></div>
</div>

<h2>Workspace Publish Conversion Rate</h2>
<table>
  <tr><th>Workspace</th><th>Uploaded</th><th>Published</th><th>PCR %</th></tr>
  {pcr_rows}
</table>

<h2>Orphaned Content (OPI)</h2>
<table>
  <tr><th>Workspace</th><th>Orphaned Videos</th><th>Orphaned Hours</th></tr>
  {opi_rows}
</table>

<p style="margin-top:40px; color:#9ca3af; font-size:0.8em;">
  Generated by Frammer AI Analytics Dashboard
</p>
</body>
</html>"""


@mcp.tool()
def generate_client_brief(client_id: str = "CLIENT_1", period: str = "last_90_days") -> str:
    """
    Generate a PDF brief for a client using WeasyPrint.

    Args:
        client_id: Client identifier (e.g. 'CLIENT_1')
        period: Time period label for the report

    Returns:
        Base64-encoded PDF bytes as a string
    """
    db = _db()

    # Funnel
    row = db.execute("""
        SELECT
          COUNT(*) FILTER (WHERE upload_date IS NOT NULL),
          COUNT(*) FILTER (WHERE processed_date IS NOT NULL),
          COUNT(*) FILTER (WHERE published_flag=true),
          ROUND(SUM(CASE WHEN published_flag=true THEN 1 ELSE 0 END)*100.0/COUNT(*),1)
        FROM frammer_dataset
    """).fetchone()
    uploaded, processed, published, pcr_total = row

    # PCR by workspace
    pcr_df = db.execute("""
        SELECT frammer_workspace, COUNT(*) AS total,
               SUM(CASE WHEN published_flag=true THEN 1 ELSE 0 END) AS pub,
               ROUND(SUM(CASE WHEN published_flag=true THEN 1 ELSE 0 END)*100.0/COUNT(*),1) AS pcr
        FROM frammer_dataset GROUP BY frammer_workspace ORDER BY pcr DESC
    """).df()
    pcr_rows = "".join(
        f"<tr><td>{r.frammer_workspace}</td><td>{int(r.total)}</td><td>{int(r.pub)}</td><td>{r.pcr}%</td></tr>"
        for r in pcr_df.itertuples()
    )

    # OPI
    opi_df = db.execute("""
        SELECT frammer_workspace,
               COUNT(*) AS orphaned_count,
               ROUND(SUM(video_duration_sec/3600.0),1) AS orphaned_hours
        FROM frammer_dataset
        WHERE published_flag=false AND TRY_CAST(upload_date AS TIMESTAMP) IS NOT NULL
          AND TRY_CAST(upload_date AS TIMESTAMP) < NOW() - INTERVAL '30 days'
        GROUP BY frammer_workspace ORDER BY orphaned_hours DESC
    """).df()
    opi_rows = "".join(
        f"<tr><td>{r.frammer_workspace}</td><td>{int(r.orphaned_count)}</td><td>{r.orphaned_hours}h</td></tr>"
        for r in opi_df.itertuples()
    )

    html = _REPORT_HTML.format(
        client_id=client_id, period=period,
        uploaded=int(uploaded), processed=int(processed),
        published=int(published), pcr_total=pcr_total,
        pcr_rows=pcr_rows, opi_rows=opi_rows,
    )

    try:
        import weasyprint
        pdf_bytes = weasyprint.HTML(string=html).write_pdf()
    except ImportError:
        # WeasyPrint not installed — return HTML as base64 fallback
        pdf_bytes = html.encode("utf-8")

    return base64.b64encode(pdf_bytes).decode("ascii")


if __name__ == "__main__":
    mcp.run()
